/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MainFooter: typeof import('./../components/Main/MainFooter.vue')['default']
    MainIntro: typeof import('./../components/Main/MainIntro.vue')['default']
    MediaAlbum: typeof import('./../components/Media/MediaAlbum.vue')['default']
    MediaIframe: typeof import('./../components/Media/MediaIframe.vue')['default']
    MediaImage: typeof import('./../components/Media/MediaImage.vue')['default']
    MediaPost: typeof import('./../components/Media/MediaPost.vue')['default']
    MediaPostContainer: typeof import('./../components/Media/MediaPostContainer.vue')['default']
    MediaPostImage: typeof import('./../components/Media/MediaPostImage.vue')['default']
    MediaReel: typeof import('./../components/Media/MediaReel.vue')['default']
    MediaVideo: typeof import('./../components/Media/MediaVideo.vue')['default']
    MediaVideoCoverSelector: typeof import('./../components/Media/MediaVideoCoverSelector.vue')['default']
    Profile: typeof import('./../components/Profile/Profile/Profile.vue')['default']
    ProfileAvatar: typeof import('./../components/Profile/Profile/ProfileAvatar.vue')['default']
    ProfileFeed: typeof import('./../components/Profile/ProfileFeed/ProfileFeed.vue')['default']
    ProfileFeedPost: typeof import('./../components/Profile/ProfileFeed/ProfileFeedPost.vue')['default']
    ProfileFeedPostHeader: typeof import('./../components/Profile/ProfileFeed/ProfileFeedPostHeader.vue')['default']
    ProfileHeader: typeof import('./../components/Profile/Profile/ProfileHeader.vue')['default']
    ProfileHeaderDesktop: typeof import('./../components/Profile/Profile/ProfileHeaderDesktop.vue')['default']
    ProfileHeaderMobile: typeof import('./../components/Profile/Profile/ProfileHeaderMobile.vue')['default']
    ProfileHeaderStats: typeof import('./../components/Profile/Profile/ProfileHeaderStats.vue')['default']
    ProfileMedia: typeof import('./../components/Media/ProfileMedia.vue')['default']
    ProfileMediaAlbum: typeof import('./../components/Media/ProfileMediaAlbum.vue')['default']
    ProfileMediaContainer: typeof import('./../components/Media/ProfileMediaContainer.vue')['default']
    ProfileMediaGrid: typeof import('./../components/Profile/Profile/ProfileMediaGrid.vue')['default']
    ProfileMediaIframe: typeof import('./../components/Media/ProfileMediaIframe.vue')['default']
    ProfileMediaImage: typeof import('./../components/Media/ProfileMediaImage.vue')['default']
    ProfileMediaVideo: typeof import('./../components/Media/ProfileMediaVideo.vue')['default']
    ProfileSwitcherCard: typeof import('./../components/Profile/ProfileSwitcher/ProfileSwitcherCard.vue')['default']
    ProfileTabs: typeof import('./../components/Profile/Profile/ProfileTabs.vue')['default']
    ToolRuler: typeof import('./../components/Tool/ToolRuler.vue')['default']
  }
}
