/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MainFooter: typeof import('./../components/Main/MainFooter.vue')['default']
    MainIntro: typeof import('./../components/Main/MainIntro.vue')['default']
    MediaAlbum: typeof import('./../components/Media/MediaType/MediaAlbum.vue')['default']
    MediaContainer: typeof import('./../components/Media/MediaContainer.vue')['default']
    MediaDetail: typeof import('./../components/Media/MediaDetail.vue')['default']
    MediaDialog: typeof import('./../components/Media/MediaDialog.vue')['default']
    MediaIframe: typeof import('./../components/Media/MediaType/MediaIframe.vue')['default']
    MediaImage: typeof import('./../components/Media/MediaType/MediaImage.vue')['default']
    MediaPost: typeof import('./../components/Media/MediaPost.vue')['default']
    MediaReel: typeof import('./../components/Media/MediaReel.vue')['default']
    MediaVideo: typeof import('./../components/Media/MediaType/MediaVideo.vue')['default']
    MediaVideoCoverSelector: typeof import('./../components/Media/MediaType/MediaVideoCoverSelector.vue')['default']
    Profile: typeof import('./../components/Profile/Profile/Profile.vue')['default']
    ProfileAvatar: typeof import('./../components/Profile/Profile/ProfileAvatar/ProfileAvatar.vue')['default']
    ProfileAvatarContainer: typeof import('./../components/Profile/Profile/ProfileAvatar/ProfileAvatarContainer.vue')['default']
    ProfileHeader: typeof import('./../components/Profile/Profile/ProfileHeader.vue')['default']
    ProfileHeaderDesktop: typeof import('./../components/Profile/Profile/ProfileHeader/ProfileHeaderDesktop.vue')['default']
    ProfileHeaderInner: typeof import('./../components/Profile/Profile/ProfileHeader/ProfileHeaderInner.vue')['default']
    ProfileHeaderMobile: typeof import('./../components/Profile/Profile/ProfileHeader/ProfileHeaderMobile.vue')['default']
    ProfileHeaderName: typeof import('./../components/Profile/Profile/ProfileHeader/ProfileHeaderName.vue')['default']
    ProfileHeaderStats: typeof import('./../components/Profile/Profile/ProfileHeader/ProfileHeaderStats.vue')['default']
    ProfileHeaderUsername: typeof import('./../components/Profile/Profile/ProfileHeader/ProfileHeaderUsername.vue')['default']
    ProfileHeaderWebsite: typeof import('./../components/Profile/Profile/ProfileHeader/ProfileHeaderWebsite.vue')['default']
    ProfileMediaGrid: typeof import('./../components/Profile/Profile/ProfileMedia/ProfileMediaGrid.vue')['default']
    ProfileMediaGridPosts: typeof import('./../components/Profile/Profile/ProfileMedia/ProfileMediaGridPosts.vue')['default']
    ProfileMediaGridReels: typeof import('./../components/Profile/Profile/ProfileMedia/ProfileMediaGridReels.vue')['default']
    ProfileSelector: typeof import('./../components/Profile/Profile/ProfileSelector/ProfileSelector.vue')['default']
    ProfileSelectorAdd: typeof import('./../components/Profile/Profile/ProfileSelector/ProfileSelectorAdd.vue')['default']
    ProfileSelectorCard: typeof import('./../components/Profile/ProfileSelector/ProfileSelectorCard.vue')['default']
    ProfileSelectorMenu: typeof import('./../components/Profile/Profile/ProfileSelector/ProfileSelectorMenu.vue')['default']
    ProfileSwitcherCard: typeof import('./../components/Profile/ProfileSelector/ProfileSwitcherCard.vue')['default']
    ProfileTabs: typeof import('./../components/Profile/Profile/ProfileTabs.vue')['default']
    ToolGuides: typeof import('./../components/Tool/ToolGuides.vue')['default']
  }
}
